/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//Step 1: enable the clock register for the  AHB1ENR where  GPIOB  is connected
    RCC_AHB1ENR_t volatile *pRCC_AHB1ENR = BASE_RCC_AHB1ENR;
    pRCC_AHB1ENR->gpio_b_en = 1;

    //Step 2: Set the mode of the GPIO to output user led2 LED BLUE PB7 137
    GPIOx_MODER_t volatile *pGPIOx_MODER = BASE_GPIOB_MODER;
    pGPIOx_MODER->moder_7 = 1; // 2 is 01 in binary 01: General purpose output mode

    //Step 3: set the GPIO port output data register
    GPIOx_ODR_t volatile *pGPIOx_ODR = BASE_GPIOB_ODR;
    pGPIOx_ODR->odr_7 = 1;


    /* Loop forever */
	for(;;);
}
